---

- name: Install prerequisites using apt-get
  become: yes
  become_user: root
  apt:
    pkg:
        - apt-transport-https
        - dnsmasq
        - fontconfig
        - git                     # Version control
        - htop                    # Server stats
        - libcrypto++-dev
        - libcups2-dev
        - libffi-dev
        - libfreetype6-dev
        - liblcms2-dev
        - libldap2-dev
        - libsasl2-dev
        - libssl-dev
        - libwebp-dev
        - libxext6
        - libxrender1
        - libxslt1-dev
        - libxslt1.1
        - ntp                     # Clock synchronization
        - postfix                 # Mail Server
        - pv                      # Show progress during database restore
        - python-tk
        - python3-dev             # Installing python developer suite
        - python3-pip
        - screen                  # To aid ssh sessions with connectivity problems
        - vim                     # Is that supposed to be a question!?
        - xfonts-75dpi
        - xfonts-base
        - zlib1g-dev
    state: present
    force: yes

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

...
