language: python
dist: xenial

python:
  - "2.7"

install:
  - sudo pip install urllib3 pyOpenSSL ndg-httpsclient pyasn1
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - sudo apt-get install --only-upgrade -y git
  - sudo apt-get install hhvm && rm -rf /home/travis/.kiex/
  - mkdir -p ~/.bench
  - mkdir -p /tmp/.bench
  - cp -r $TRAVIS_BUILD_DIR/* ~/.bench
  - cp -r $TRAVIS_BUILD_DIR/* /tmp/.bench
  - sudo python $TRAVIS_BUILD_DIR/playbooks/install.py --user travis --run-travis --production --verbose

script:
  - cd ~
  - sudo pip install --upgrade pip
  - sudo pip install -e ~/.bench
  - sudo python -m unittest -v bench.tests.test_setup_production
