language: python
dist: xenial

python:
  - "3.6"

addons:
  apt:
    packages:
      - hhvm
      - python3-apt

install:
  - pip install -r requirements.txt
  - sudo apt-get purge -y mysql-common mysql-server mysql-client
  - rm -rf /home/travis/.kiex/
  - mkdir -p ~/.bench
  - mkdir -p /tmp/.bench
  - cp -r $TRAVIS_BUILD_DIR/* ~/.bench
  - cp -r $TRAVIS_BUILD_DIR/* /tmp/.bench
  - python $TRAVIS_BUILD_DIR/playbooks/install.py --user travis --run-travis --production --verbose

script:
  - cd ~
  - pip install --upgrade pip
  - pip install -e ~/.bench
  - python -m unittest -v bench.tests.test_setup_production
