version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Python
          command: |
            sudo pip install --ignore-installed setuptools
            sudo pip install urllib3 pyOpenSSL ndg-httpsclient pyasn1

      - run:
          name: Setup Directories
          command: |
            mkdir -p ~/.bench
            mkdir -p /tmp/.bench
            cp -r ~/repo/* ~/.bench
            cp -r ~/repo/* /tmp/.bench

      - run:
          name: Install Bench (Production)
          command: sudo python ~/repo/playbooks/install.py --user travis --run-travis --production

      - run:
          name: Setup Tests
          command: |
            cd ~
            sudo pip install --upgrade pip
            sudo pip install -e ~/.bench

      - run:
          name: Run Tests
          command: sudo -E python -m unittest -v bench.tests.test_setup_production
